# Generated by Django 5.1.11 on 2025-08-08 13:32

import accounts.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(help_text='Format : +237XXXXXXXXX ou format international', max_length=20, unique=True, validators=[accounts.validators.validate_cameroon_phone], verbose_name='Numéro de téléphone')),
                ('account_type', models.CharField(choices=[('individual', 'Personne physique'), ('company', 'Entreprise')], default='individual', help_text="Type d'utilisateur : personne physique ou entreprise", max_length=20, verbose_name='Type de compte')),
                ('is_verified', models.BooleanField(default=False, help_text='Indique si le numéro de téléphone a été vérifié par SMS', verbose_name='Téléphone vérifié')),
                ('language_preference', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', help_text="Langue d'interface préférée de l'utilisateur", max_length=5, verbose_name='Langue préférée')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur MAVECAM',
                'verbose_name_plural': 'Utilisateurs MAVECAM',
                'db_table': 'accounts_user',
            },
        ),
    ]
