# Generated by Django 5.1.11 on 2025-08-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, help_text='Nom de l\'entreprise pour les comptes de type "company"', max_length=200, null=True, verbose_name="Nom de l'entreprise"),
        ),
    ]
