# Generated by Django 5.1.11 on 2025-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('alevins', "Producteur d'alevins"), ('poisson_table', 'Producteur de poisson de table'), ('mixte', 'Production mixte (alevins et poisson de table)')], help_text="Maillon d'activité : producteur d'alevins, poisson de table, etc.", max_length=20, null=True, verbose_name="Type d'activité"),
        ),
        migrations.AddField(
            model_name='user',
            name='age_group',
            field=models.CharField(blank=True, choices=[('18_25', '18-25 ans'), ('26_35', '26-35 ans'), ('36_45', '36-45 ans'), ('46_55', '46-55 ans'), ('56_65', '56-65 ans'), ('65_plus', '65 ans et plus')], help_text="Tranche d'âge de la personne", max_length=10, null=True, verbose_name="Classe d'âge"),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Département dans la région choisie', max_length=50, null=True, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, help_text='Arrondissement dans le département', max_length=100, null=True, verbose_name='Arrondissement'),
        ),
        migrations.AddField(
            model_name='user',
            name='intervention_zone',
            field=models.CharField(blank=True, help_text="Zone géographique d'intervention de l'activité", max_length=200, null=True, verbose_name="Zone d'intervention"),
        ),
        migrations.AddField(
            model_name='user',
            name='legal_status',
            field=models.CharField(blank=True, choices=[('ei', 'Entreprise Individuelle (EI)'), ('scoop', 'Coopérative Simplifiée (SCOOP)'), ('coop_ca', "Coopérative avec Conseil d'Administration (Coop-CA)"), ('sarl', 'Société à Responsabilité Limitée (SARL)'), ('sarlu', 'SARL Unipersonnelle (SARLU)'), ('sa', 'Société Anonyme (SA)'), ('sas', 'Société par Actions Simplifiée (SAS)'), ('sasu', 'SAS Unipersonnelle (SASU)'), ('snc', 'Société en Nom Collectif (SNC)'), ('scs', 'Société en Commandite Simple (SCS)'), ('sci', 'Société Civile Immobilière (SCI)'), ('autre', 'Autre statut juridique')], help_text="Statut juridique de l'entreprise (SARL, SCOOP, etc.)", max_length=20, null=True, verbose_name='Statut juridique'),
        ),
        migrations.AddField(
            model_name='user',
            name='neighborhood',
            field=models.CharField(blank=True, help_text='Quartier ou localité spécifique', max_length=100, null=True, verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='user',
            name='promoter_name',
            field=models.CharField(blank=True, help_text="Nom du promoteur ou dirigeant de l'entreprise", max_length=200, null=True, verbose_name='Nom du promoteur'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('adamaoua', 'Adamaoua'), ('centre', 'Centre'), ('est', 'Est'), ('extreme_nord', 'Extrême-Nord'), ('littoral', 'Littoral'), ('nord', 'Nord'), ('nord_ouest', 'Nord-Ouest'), ('ouest', 'Ouest'), ('sud', 'Sud'), ('sud_ouest', 'Sud-Ouest')], help_text='Région administrative du Cameroun', max_length=20, null=True, verbose_name='Région'),
        ),
    ]
