# Generated by Django 5.1.11 on 2025-08-08 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_activity_type_user_age_group_user_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique UUID pour la synchronisation mobile', primary_key=True, serialize=False)),
                ('farm_name', models.CharField(help_text="Nom commercial ou descriptif de l'exploitation", max_length=200, verbose_name='Nom de la ferme')),
                ('certification_status', models.CharField(choices=[('pending', 'En attente'), ('certified', 'Certifiée'), ('suspended', 'Suspendue'), ('rejected', 'Rejetée')], default='pending', help_text='Statut de certification géré uniquement par les admins MAVECAM', max_length=20, verbose_name='Statut de certification')),
                ('certification_date', models.DateTimeField(blank=True, help_text='Date à laquelle la ferme a été certifiée', null=True, verbose_name='Date de certification')),
                ('certification_notes', models.TextField(blank=True, help_text='Notes internes MAVECAM sur le processus de certification', verbose_name='Notes de certification')),
                ('total_ponds', models.PositiveIntegerField(default=0, help_text="Nombre total de bassins d'élevage disponibles", verbose_name='Nombre total de bassins')),
                ('total_area_m2', models.DecimalField(blank=True, decimal_places=2, help_text="Superficie totale de l'exploitation en mètres carrés", max_digits=10, null=True, verbose_name='Superficie totale (m²)')),
                ('water_source', models.CharField(blank=True, help_text="Principale source d'approvisionnement en eau", max_length=100, verbose_name="Source d'eau")),
                ('main_species', models.CharField(blank=True, help_text='Principale espèce de poisson élevée', max_length=100, verbose_name='Espèce principale')),
                ('annual_production_kg', models.PositiveIntegerField(blank=True, help_text='Production annuelle estimée en kilogrammes', null=True, verbose_name='Production annuelle (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création automatique du profil', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification du profil', verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(default=False, help_text='Marqueur de suppression pour la synchronisation mobile', verbose_name='Supprimé')),
                ('user', models.OneToOneField(help_text='Utilisateur propriétaire de cette ferme', on_delete=django.db.models.deletion.CASCADE, related_name='farm_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil de ferme',
                'verbose_name_plural': 'Profils de fermes',
                'db_table': 'accounts_farm_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
