# Generated by Django 5.1.11 on 2025-08-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_farmprofile'),
    ]

    operations = [
        # Supprimer les champs non essentiels pour le MVP
        migrations.RemoveField(
            model_name='farmprofile',
            name='certification_date',
        ),
        migrations.RemoveField(
            model_name='farmprofile',
            name='certification_notes',
        ),
    ]
