# Generated by Django 5.1.11 on 2025-08-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20250808_2315'),
    ]

    operations = [
    ]
