# Generated by Django 5.1.11 on 2026-04-17 09:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminViewState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('cycle_logs', 'Logs de cycle'), ('sanitary_logs', 'Journaux sanitaires'), ('orders', 'Commandes')], max_length=50, verbose_name='Section')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière consultation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_view_states', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur admin')),
            ],
            options={
                'verbose_name': 'État de vue admin',
                'verbose_name_plural': 'États de vue admin',
                'db_table': 'common_admin_view_state',
                'unique_together': {('user', 'section')},
            },
        ),
    ]
