# Generated by Django 5.1.11 on 2026-04-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminviewstate',
            name='section',
            field=models.CharField(choices=[('cycle_logs', 'Logs de cycle'), ('sanitary_logs', 'Journaux sanitaires'), ('orders', 'Commandes'), ('production_reports', 'Rapports de production'), ('dispatch_logs', "Journaux d'envoi")], max_length=50, verbose_name='Section'),
        ),
    ]
