# Generated by Django 5.1.11 on 2026-08-14 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_remove_farmprofile_production_fields"),
        ("aquaculture", "0051_validate_ongoing_baseline_not_null"),
        ("common", "0002_alter_adminviewstate_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActivityEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("aquaculture.production_unit.created", "Unité de production créée"),
                            ("aquaculture.production_cycle.created", "Cycle de production créé"),
                            ("aquaculture.cycle_log.received", "Journal de cycle reçu"),
                            ("aquaculture.sanitary_log.created", "Événement sanitaire créé"),
                            ("aquaculture.sanitary_log.resolved", "Événement sanitaire résolu"),
                            ("aquaculture.calibration.completed", "Calibrage terminé"),
                            ("aquaculture.final_harvest.completed", "Récolte finale terminée"),
                            ("aquaculture.production_report.generated", "Rapport de production généré"),
                            ("aquaculture.report_dispatch.succeeded", "Envoi de rapport réussi"),
                            ("aquaculture.report_dispatch.failed", "Envoi de rapport échoué"),
                            ("commerce.order.created", "Commande créée"),
                            ("commerce.order.delivered", "Commande livrée"),
                            ("commerce.order.ready_for_pickup", "Commande prête au retrait"),
                            ("commerce.order.received", "Commande reçue"),
                            ("support.user_message.received", "Message utilisateur reçu"),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[("aquaculture", "Aquaculture"), ("commerce", "Commerce"), ("support", "Support")],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "Information"), ("attention", "Attention"), ("critical", "Critique")],
                        max_length=20,
                    ),
                ),
                ("source_app_label", models.CharField(max_length=64)),
                ("source_model", models.CharField(max_length=64)),
                ("source_object_id", models.UUIDField()),
                ("occurred_on", models.DateField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("source_recorded_at", models.DateTimeField(blank=True, null=True)),
                ("projected_at", models.DateTimeField(auto_now_add=True)),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                ("render_context", models.JSONField(default=dict)),
                ("render_version", models.PositiveSmallIntegerField(default=1)),
                ("is_backfilled", models.BooleanField(default=False)),
                (
                    "farm_profile",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_activity_events",
                        to="accounts.farmprofile",
                    ),
                ),
                (
                    "production_cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_activity_events",
                        to="aquaculture.productioncycle",
                    ),
                ),
                (
                    "production_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_activity_events",
                        to="aquaculture.productionunit",
                    ),
                ),
            ],
            options={
                "db_table": "common_admin_activity_event",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["domain", "-id"], name="admin_act_domain_id_idx"),
                    models.Index(fields=["event_type", "-id"], name="admin_act_type_id_idx"),
                    models.Index(fields=["farm_profile", "-id"], name="admin_act_farm_id_idx"),
                    models.Index(fields=["level", "-id"], name="admin_act_level_id_idx"),
                    models.Index(fields=["occurred_on"], name="admin_act_on_idx"),
                    models.Index(fields=["occurred_at"], name="admin_act_at_idx"),
                    models.Index(
                        fields=["source_app_label", "source_model", "source_object_id"], name="admin_act_source_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("occurred_at__isnull", True), ("occurred_on__isnull", False)),
                            models.Q(("occurred_at__isnull", False), ("occurred_on__isnull", True)),
                            _connector="OR",
                        ),
                        name="admin_activity_exactly_one_occurred",
                    )
                ],
            },
        ),
    ]
