# Generated by Django 5.2.17 on 2026-09-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_adminactivityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivityevent',
            name='event_type',
            field=models.CharField(choices=[('aquaculture.production_unit.created', 'Unité de production créée'), ('aquaculture.production_cycle.created', 'Cycle de production créé'), ('aquaculture.cycle_log.received', 'Journal de cycle reçu'), ('aquaculture.sanitary_log.created', 'Événement sanitaire créé'), ('aquaculture.sanitary_log.resolved', 'Événement sanitaire résolu'), ('aquaculture.calibration.completed', 'Calibrage terminé'), ('aquaculture.final_harvest.completed', 'Récolte finale terminée'), ('aquaculture.production_report.generated', 'Rapport de production généré'), ('aquaculture.report_dispatch.succeeded', 'Envoi de rapport réussi'), ('aquaculture.report_dispatch.failed', 'Envoi de rapport échoué'), ('commerce.order.created', 'Commande créée'), ('commerce.order.delivered', 'Commande livrée'), ('commerce.order.ready_for_pickup', 'Commande prête au retrait'), ('commerce.order.received', 'Commande reçue'), ('commerce.order.cancelled', 'Commande annulée'), ('support.user_message.received', 'Message utilisateur reçu')], max_length=80),
        ),
    ]
