# Generated by Django 5.1.11 on 2025-12-05 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='Notifications in-app activées')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Notifications email activées')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Notifications push activées')),
                ('feeding_reminders', models.BooleanField(default=True, verbose_name='Rappels nourrissage')),
                ('sampling_reminders', models.BooleanField(default=True, verbose_name='Rappels échantillonnage')),
                ('sanitary_alerts', models.BooleanField(default=True, verbose_name='Alertes sanitaires')),
                ('cycle_milestones', models.BooleanField(default=True, verbose_name='Étapes du cycle')),
                ('mortality_alerts', models.BooleanField(default=True, verbose_name='Alertes mortalité')),
                ('water_quality_alerts', models.BooleanField(default=True, verbose_name='Alertes qualité eau')),
                ('order_confirmations', models.BooleanField(default=True, verbose_name='Confirmations de commande')),
                ('order_status_updates', models.BooleanField(default=True, verbose_name='Mises à jour statut commande')),
                ('delivery_notifications', models.BooleanField(default=True, verbose_name='Notifications de livraison')),
                ('product_recommendations', models.BooleanField(default=False, help_text='Marketing opt-in', verbose_name='Recommandations produits')),
                ('price_alerts', models.BooleanField(default=False, help_text='Marketing opt-in', verbose_name='Alertes de prix')),
                ('ticket_updates', models.BooleanField(default=True, verbose_name='Mises à jour tickets')),
                ('support_messages', models.BooleanField(default=True, verbose_name='Messages support')),
                ('chat_messages', models.BooleanField(default=True, verbose_name='Messages chat')),
                ('chat_mentions', models.BooleanField(default=True, verbose_name='Mentions chat')),
                ('system_alerts', models.BooleanField(default=True, verbose_name='Alertes système')),
                ('account_security', models.BooleanField(default=True, verbose_name='Sécurité compte')),
                ('email_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Quotidien (résumé)'), ('weekly', 'Hebdomadaire (résumé)'), ('never', 'Jamais')], default='instant', max_length=20, verbose_name='Fréquence email')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Ex: 22:00', null=True, verbose_name='Début heures silencieuses')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Ex: 07:00', null=True, verbose_name='Fin heures silencieuses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créées le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiées le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférences de notifications',
                'verbose_name_plural': 'Préférences de notifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('notification_type', models.CharField(choices=[('feeding_reminder', 'Rappel nourrissage'), ('sampling_reminder', 'Rappel échantillonnage'), ('treatment_reminder', 'Rappel traitement'), ('cycle_milestone', 'Étape du cycle'), ('mortality_alert', 'Alerte mortalité'), ('growth_alert', 'Alerte croissance'), ('water_quality_alert', 'Alerte qualité eau'), ('harvest_reminder', 'Rappel récolte'), ('alert', 'Alerte générale'), ('order_confirmed', 'Commande confirmée'), ('order_shipped', 'Commande expédiée'), ('order_delivered', 'Commande livrée'), ('order_cancelled', 'Commande annulée'), ('payment_received', 'Paiement reçu'), ('delivery_scheduled', 'Livraison programmée'), ('product_recommendation', 'Recommandation produit'), ('low_stock_alert', 'Stock faible'), ('price_drop', 'Baisse de prix'), ('ticket_created', 'Ticket créé'), ('ticket_reply', 'Réponse ticket'), ('ticket_resolved', 'Ticket résolu'), ('ticket_reopened', 'Ticket réouvert'), ('ticket_assigned', 'Ticket assigné'), ('new_message', 'Nouveau message'), ('message_reply', 'Réponse message'), ('mention', 'Mention'), ('chat_invitation', 'Invitation chat'), ('group_created', 'Groupe créé'), ('system_update', 'Mise à jour système'), ('account_security', 'Sécurité compte'), ('maintenance', 'Maintenance'), ('welcome', 'Bienvenue'), ('password_reset', 'Réinitialisation mot de passe'), ('email_verification', 'Vérification email')], max_length=50, verbose_name='Type de notification')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorité')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données contextuelles supplémentaires', verbose_name='Métadonnées')),
                ('channels', models.JSONField(blank=True, default=list, help_text="Ex: ['in_app', 'email', 'push']", verbose_name='Canaux de diffusion')),
                ('scheduled_for', models.DateTimeField(help_text="Date/heure d'affichage de la notification", verbose_name='Programmée pour')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Envoyée')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lue le')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email envoyé le')),
                ('email_error', models.TextField(blank=True, null=True, verbose_name='Erreur email')),
                ('push_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Push envoyé le')),
                ('push_error', models.TextField(blank=True, null=True, verbose_name='Erreur push')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['user', 'is_read', 'scheduled_for'], name='notificatio_user_id_324b9c_idx'), models.Index(fields=['notification_type', 'is_sent'], name='notificatio_notific_4caeff_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx'), models.Index(fields=['scheduled_for', 'is_sent'], name='notificatio_schedul_5d6388_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expo_push_token', models.CharField(max_length=255, unique=True, verbose_name='Token Expo Push')),
                ('device_id', models.CharField(help_text='Identifiant unique du device', max_length=255, verbose_name='ID Device')),
                ('device_name', models.CharField(blank=True, help_text='Ex: iPhone 13, Samsung Galaxy S21', max_length=100, null=True, verbose_name='Nom du device')),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10, null=True, verbose_name='Plateforme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='Dernière utilisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Token Push',
                'verbose_name_plural': 'Tokens Push',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_47d48f_idx'), models.Index(fields=['expo_push_token'], name='notificatio_expo_pu_8ef804_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
