# Generated by Django 5.1.11 on 2026-07-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_chat_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('feeding_reminder', 'Rappel nourrissage'), ('sampling_reminder', 'Rappel échantillonnage'), ('treatment_reminder', 'Rappel traitement'), ('cycle_milestone', 'Étape du cycle'), ('mortality_alert', 'Alerte mortalité'), ('growth_alert', 'Alerte croissance'), ('water_quality_alert', 'Alerte qualité eau'), ('harvest_reminder', 'Rappel récolte'), ('alert', 'Alerte générale'), ('order_confirmed', 'Commande confirmée'), ('order_shipped', 'Commande expédiée'), ('order_delivered', 'Commande livrée'), ('order_ready_for_pickup', 'Commande prête au retrait'), ('order_cancelled', 'Commande annulée'), ('payment_received', 'Paiement reçu'), ('delivery_scheduled', 'Livraison programmée'), ('product_recommendation', 'Recommandation produit'), ('low_stock_alert', 'Stock faible'), ('price_drop', 'Baisse de prix'), ('ticket_created', 'Ticket créé'), ('ticket_reply', 'Réponse ticket'), ('ticket_resolved', 'Ticket résolu'), ('ticket_reopened', 'Ticket réouvert'), ('ticket_assigned', 'Ticket assigné'), ('new_message', 'Nouveau message'), ('message_reply', 'Réponse message'), ('mention', 'Mention'), ('chat_invitation', 'Invitation chat'), ('group_created', 'Groupe créé'), ('system_update', 'Mise à jour système'), ('account_security', 'Sécurité compte'), ('maintenance', 'Maintenance'), ('welcome', 'Bienvenue'), ('password_reset', 'Réinitialisation mot de passe'), ('email_verification', 'Vérification email')], max_length=50, verbose_name='Type de notification'),
        ),
    ]
