# Generated by Django 5.2.17 on 2026-09-29 19:36

from django.db import migrations, models


KEPT_NOTIFICATION_TYPES = (
    "order_confirmed",
    "order_delivered",
    "order_ready_for_pickup",
    "new_message",
)


def purge_retired_notifications(apps, schema_editor):
    """Supprime les notifications des types retirés (rappels, alertes, emails)."""
    Notification = apps.get_model("notifications", "Notification")
    Notification.objects.exclude(notification_type__in=KEPT_NOTIFICATION_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RunPython(purge_retired_notifications, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='notification',
            name='email_error',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_sent_at',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='account_security',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='chat_mentions',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='chat_messages',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='cycle_milestones',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='delivery_notifications',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_frequency',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='feeding_reminders',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='mortality_alerts',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='price_alerts',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='product_recommendations',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sampling_reminders',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sanitary_alerts',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='system_alerts',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='ticket_updates',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='water_quality_alerts',
        ),
        migrations.AlterField(
            model_name='notification',
            name='channels',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['in_app', 'push']", verbose_name='Canaux de diffusion'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_confirmed', 'Commande enregistrée'), ('order_delivered', 'Commande livrée'), ('order_ready_for_pickup', 'Commande prête au retrait'), ('new_message', 'Nouveau message')], max_length=50, verbose_name='Type de notification'),
        ),
    ]
