# Generated by Django 5.2.17 on 2026-09-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_prune_notification_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_confirmed', 'Commande enregistrée'), ('order_delivered', 'Commande livrée'), ('order_ready_for_pickup', 'Commande prête au retrait'), ('order_cancelled', 'Commande annulée'), ('new_message', 'Nouveau message')], max_length=50, verbose_name='Type de notification'),
        ),
    ]
