# Generated by Django 5.1.11 on 2025-08-25 14:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('tilapia', 'Tilapia'), ('clarias', 'Clarias (Silure)')], max_length=50, verbose_name='Espèce')),
                ('growth_stage', models.CharField(choices=[('alevin', 'Alevin (0-10g)'), ('juvenile', 'Juvénile (10-50g)'), ('croissance', 'Croissance (50-150g)'), ('finition', 'Finition (>150g)')], max_length=50, verbose_name='Stade de croissance')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Poids minimum (g)')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Poids maximum (g)')),
                ('feeding_rate_percentage', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('15'))], verbose_name="Taux d'alimentation (% biomasse/jour)")),
                ('protein_requirement', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(50)], verbose_name='Besoin en protéines (%)')),
                ('meals_per_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Repas par jour')),
                ('feed_size_mm', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Taille granulés (mm)')),
                ('recommended_products', models.JSONField(default=list, help_text='Liste des références produits MAVECAM', verbose_name='Produits recommandés')),
                ('expected_fcr', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('3.0'))], verbose_name='FCR attendu')),
                ('feeding_notes', models.TextField(blank=True, verbose_name="Notes d'alimentation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['species', 'min_weight'],
                'unique_together': {('species', 'growth_stage')},
            },
        ),
        migrations.CreateModel(
            name='ProductionCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_name', models.CharField(help_text="Ex: 'Cycle Tilapia Q1 2024'", max_length=100, verbose_name='Nom du cycle')),
                ('species', models.CharField(choices=[('tilapia', 'Tilapia'), ('clarias', 'Clarias (Silure)')], max_length=50, verbose_name='Espèce')),
                ('pond_identifier', models.CharField(help_text="Ex: 'Bassin A', 'Étang 1'", max_length=50, verbose_name='Identifiant du bassin')),
                ('pond_surface_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Surface du bassin (m²)')),
                ('pond_volume_m3', models.DecimalField(blank=True, decimal_places=2, help_text='Optionnel - pour calcul densité', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Volume du bassin (m³)')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('initial_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='Nombre initial de poissons')),
                ('initial_average_weight', models.DecimalField(decimal_places=2, help_text='8-15g typiquement pour alevins', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Poids moyen initial (g)')),
                ('initial_biomass', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement', max_digits=10, verbose_name='Biomasse initiale (kg)')),
                ('current_count', models.PositiveIntegerField(help_text='Mis à jour après chaque mortalité', verbose_name='Effectif actuel')),
                ('current_average_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Poids moyen actuel (g)')),
                ('current_biomass', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Biomasse actuelle (kg)')),
                ('total_feed_consumed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Aliment total consommé (kg)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de récolte')),
                ('final_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre final de poissons')),
                ('final_average_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids moyen final (g)')),
                ('final_biomass', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Biomasse finale (kg)')),
                ('survival_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taux de survie (%)')),
                ('fcr', models.DecimalField(blank=True, decimal_places=2, help_text='Feed Conversion Ratio', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Indice de consommation (FCR)')),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('active', 'En cours'), ('harvested', 'Récolté'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_cycles', to='accounts.farmprofile', verbose_name='Profil de ferme')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('feeding_reminder', 'Rappel nourrissage'), ('sampling_reminder', 'Rappel échantillonnage'), ('treatment_reminder', 'Rappel traitement'), ('cycle_milestone', 'Étape du cycle'), ('alert', 'Alerte')], max_length=50, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('scheduled_for', models.DateTimeField(verbose_name='Programmé pour')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Envoyé')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquaculture_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aquaculture.productioncycle', verbose_name='Cycle concerné')),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='FeedingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(help_text='Semaine depuis le début du cycle', verbose_name='Numéro de semaine')),
                ('estimated_fish_count', models.PositiveIntegerField(verbose_name='Effectif estimé')),
                ('average_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Poids moyen (g)')),
                ('biomass', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Biomasse (kg)')),
                ('daily_feed_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantité journalière (kg)')),
                ('feeding_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name="Taux d'alimentation (% biomasse)")),
                ('meals_per_day', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Repas par jour')),
                ('feed_per_meal', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantité par repas (kg)')),
                ('recommended_feed_type', models.CharField(max_length=100, verbose_name="Type d'aliment recommandé")),
                ('feed_size_mm', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Taille granulés (mm)')),
                ('protein_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(50)], verbose_name='% protéines')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='aquaculture.productioncycle', verbose_name='Cycle de production')),
            ],
            options={
                'ordering': ['cycle', 'week_number'],
            },
        ),
        migrations.CreateModel(
            name='CycleMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_curve_data', models.JSONField(default=list, help_text="Format: [{'date': 'YYYY-MM-DD', 'weight': float}, ...]", verbose_name='Données courbe de croissance')),
                ('daily_growth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de croissance journalier (g/jour)')),
                ('specific_growth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de croissance spécifique (%/jour)')),
                ('survival_curve_data', models.JSONField(default=list, help_text="Format: [{'date': 'YYYY-MM-DD', 'count': int}, ...]", verbose_name='Données courbe de survie')),
                ('weekly_mortality_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de mortalité hebdomadaire (%)')),
                ('cumulative_feed_data', models.JSONField(default=list, help_text="Format: [{'date': 'YYYY-MM-DD', 'total_feed': float}, ...]", verbose_name='Données alimentation cumulée')),
                ('average_daily_feed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Alimentation journalière moyenne (kg)')),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Score de performance (0-100)')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='aquaculture.productioncycle', verbose_name='Cycle de production')),
            ],
        ),
        migrations.CreateModel(
            name='CycleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(blank=True, help_text='UUID généré côté mobile pour déduplication', null=True, unique=True, verbose_name='UUID client')),
                ('log_date', models.DateField(verbose_name='Date du log')),
                ('log_time', models.TimeField(auto_now_add=True, verbose_name='Heure de saisie')),
                ('mortality_count', models.PositiveIntegerField(default=0, help_text='Poissons morts observés ce jour', verbose_name='Nombre de morts')),
                ('mortality_reason', models.CharField(blank=True, help_text='Si connue', max_length=100, verbose_name='Cause de mortalité')),
                ('sample_count', models.PositiveIntegerField(blank=True, help_text='Minimum 20 recommandé pour échantillonnage', null=True, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Nombre de poissons pesés')),
                ('sample_total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Poids total échantillon (g)')),
                ('average_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Calculé automatiquement ou saisi manuellement', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Poids moyen (g)')),
                ('feed_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Quantité d'aliment (kg)")),
                ('feed_type', models.CharField(blank=True, help_text='Référence produit MAVECAM', max_length=100, verbose_name="Type d'aliment")),
                ('feeding_times', models.JSONField(blank=True, default=list, help_text='Liste des heures de distribution', verbose_name='Heures de nourrissage')),
                ('water_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('50'))], verbose_name="Température de l'eau (°C)")),
                ('dissolved_oxygen', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='Oxygène dissous (mg/L)')),
                ('ph_level', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('14'))], verbose_name='pH')),
                ('ammonia_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Niveau d'ammoniac (ppm)")),
                ('observations', models.TextField(blank=True, help_text='Notes et remarques diverses', verbose_name='Observations')),
                ('created_offline', models.BooleanField(default=False, verbose_name='Créé hors ligne')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synchronisé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='aquaculture.productioncycle', verbose_name='Cycle de production')),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='SanitaryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField(verbose_name="Date de l'événement")),
                ('event_type', models.CharField(choices=[('disease', 'Maladie'), ('treatment', 'Traitement'), ('vaccination', 'Vaccination'), ('abnormal_mortality', 'Mortalité anormale'), ('water_quality', "Problème qualité d'eau"), ('other', 'Autre')], max_length=50, verbose_name="Type d'événement")),
                ('symptoms', models.TextField(help_text='Description détaillée des symptômes', verbose_name='Symptômes observés')),
                ('affected_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de poissons affectés')),
                ('treatment_applied', models.TextField(blank=True, verbose_name='Traitement appliqué')),
                ('medication_used', models.CharField(blank=True, max_length=200, verbose_name='Médicament utilisé')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='Dosage')),
                ('treatment_duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée du traitement (jours)')),
                ('photo', models.ImageField(blank=True, help_text='Compressée automatiquement côté mobile', null=True, upload_to='sanitary_logs/%Y/%m/', verbose_name='Photo')),
                ('resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('resolution_date', models.DateField(blank=True, null=True, verbose_name='Date de résolution')),
                ('notes', models.TextField(blank=True, verbose_name='Notes additionnelles')),
                ('created_offline', models.BooleanField(default=False, verbose_name='Créé hors ligne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanitary_logs', to='aquaculture.productioncycle', verbose_name='Cycle de production')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.AddIndex(
            model_name='productioncycle',
            index=models.Index(fields=['farm_profile', 'status'], name='aquaculture_farm_pr_cc80fc_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncycle',
            index=models.Index(fields=['start_date', 'end_date'], name='aquaculture_start_d_52c03a_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncycle',
            index=models.Index(fields=['species', 'status'], name='aquaculture_species_974d05_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'scheduled_for'], name='aquaculture_user_id_24a347_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'is_sent'], name='aquaculture_notific_cb6772_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedingplan',
            unique_together={('cycle', 'week_number')},
        ),
        migrations.AddIndex(
            model_name='cyclelog',
            index=models.Index(fields=['cycle', 'log_date'], name='aquaculture_cycle_i_2f0be1_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclelog',
            index=models.Index(fields=['client_uuid'], name='aquaculture_client__c1a91d_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclelog',
            index=models.Index(fields=['created_offline', 'synced_at'], name='aquaculture_created_b9bbd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cyclelog',
            unique_together={('cycle', 'log_date')},
        ),
        migrations.AddIndex(
            model_name='sanitarylog',
            index=models.Index(fields=['cycle', 'event_date'], name='aquaculture_cycle_i_fd25f8_idx'),
        ),
        migrations.AddIndex(
            model_name='sanitarylog',
            index=models.Index(fields=['event_type', 'resolved'], name='aquaculture_event_t_7ef46b_idx'),
        ),
        migrations.AddIndex(
            model_name='sanitarylog',
            index=models.Index(fields=['created_offline'], name='aquaculture_created_0a9bd9_idx'),
        ),
    ]
