# Generated by Django 5.1.11 on 2025-09-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyclelog',
            options={'ordering': ['-log_date'], 'verbose_name': 'Journal quotidien', 'verbose_name_plural': 'Journaux quotidiens'},
        ),
        migrations.AlterModelOptions(
            name='cyclemetrics',
            options={'verbose_name': 'Métrique de cycle', 'verbose_name_plural': 'Métriques de cycles'},
        ),
        migrations.AlterModelOptions(
            name='feedingplan',
            options={'ordering': ['cycle', 'week_number'], 'verbose_name': "Plan d'alimentation", 'verbose_name_plural': "Plans d'alimentation"},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-scheduled_for'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='nutritionalguide',
            options={'ordering': ['species', 'min_weight'], 'verbose_name': 'Guide nutritionnel', 'verbose_name_plural': 'Guides nutritionnels'},
        ),
        migrations.AlterModelOptions(
            name='productioncycle',
            options={'ordering': ['-start_date'], 'verbose_name': 'Cycle de production', 'verbose_name_plural': 'Cycles de production'},
        ),
        migrations.AlterModelOptions(
            name='sanitarylog',
            options={'ordering': ['-event_date'], 'verbose_name': 'Journal sanitaire', 'verbose_name_plural': 'Journaux sanitaires'},
        ),
    ]
