# Generated by Django 5.1.15 on 2025-12-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0002_alter_cyclelog_options_alter_cyclemetrics_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
