# Generated by Django 5.1.15 on 2025-12-09 10:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0003_remove_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncycle',
            name='pond_surface_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optionnel - au moins surface OU volume requis', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Surface du bassin (m²)'),
        ),
        migrations.AlterField(
            model_name='productioncycle',
            name='pond_volume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optionnel - au moins surface OU volume requis', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Volume du bassin (m³)'),
        ),
    ]
