# Generated by Django 5.1.15 on 2026-02-23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_default_feed_price'),
        ('aquaculture', '0004_make_pond_surface_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily', 'Journalier'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], max_length=20, verbose_name='Type de rapport')),
                ('period_start', models.DateField(verbose_name='Début période')),
                ('period_end', models.DateField(verbose_name='Fin période')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé')], default='draft', max_length=20, verbose_name='Statut')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Snapshot des données utilisées pour la génération', verbose_name='Données du rapport')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Fichier PDF')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Généré le')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('email_status', models.CharField(choices=[('not_sent', 'Non envoyé'), ('sent', 'Envoyé'), ('failed', 'Échec')], default='not_sent', max_length=20, verbose_name='Statut email')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email envoyé le')),
                ('whatsapp_status', models.CharField(choices=[('not_shared', 'Non partagé'), ('shared', 'Partagé')], default='not_shared', max_length=20, verbose_name='Statut WhatsApp')),
                ('whatsapp_shared_at', models.DateTimeField(blank=True, null=True, verbose_name='Partagé sur WhatsApp le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_reports', to='accounts.farmprofile', verbose_name='Profil de ferme')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_reports', to='accounts.user', verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Rapport de production',
                'verbose_name_plural': 'Rapports de production',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDispatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='Canal')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='Destinataire')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failed', 'Échec')], max_length=20, verbose_name='Statut')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='Code erreur')),
                ('error_message', models.TextField(blank=True, verbose_name='Message erreur')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_dispatch_logs', to='accounts.user', verbose_name='Action effectuée par')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='aquaculture.productionreport', verbose_name='Rapport')),
            ],
            options={
                'verbose_name': "Journal d'envoi de rapport",
                'verbose_name_plural': "Journaux d'envoi de rapports",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionreport',
            constraint=models.UniqueConstraint(fields=('farm_profile', 'report_type', 'period_start', 'period_end'), name='uniq_report_period_per_farm'),
        ),
        migrations.AddIndex(
            model_name='productionreport',
            index=models.Index(fields=['farm_profile', 'report_type', 'period_start'], name='rpt_farm_type_start_idx'),
        ),
        migrations.AddIndex(
            model_name='productionreport',
            index=models.Index(fields=['status', 'generated_at'], name='rpt_status_generated_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdispatchlog',
            index=models.Index(fields=['report', 'channel', 'created_at'], name='rptlog_report_chan_idx'),
        ),
    ]
