# Generated by Django 5.1.11 on 2026-03-30 13:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0011_add_pending_status_to_production_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalguide',
            name='growth_stage',
            field=models.CharField(choices=[('alevin', 'Alevin (0-10g)'), ('juvenile', 'Juvénile (10-50g)'), ('croissance', 'Croissance (50-150g)'), ('finition', 'Finition (150-500g)'), ('pre_recolte', 'Pré-récolte (>500g)')], max_length=50, verbose_name='Stade de croissance'),
        ),
        migrations.AlterField(
            model_name='nutritionalguide',
            name='recommended_products',
            field=models.JSONField(default=list, help_text="Liste des références produits (ex: ['DIBAQ Catfish 2mm'])", verbose_name='Produits recommandés'),
        ),
        migrations.AlterField(
            model_name='productioncycle',
            name='target_harvest_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids moyen cible utilisé pour la projection économique', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('50'))], verbose_name='Poids cible récolte (g)'),
        ),
    ]
