# Generated by Django 5.1.11 on 2026-04-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0012_order_production_cycle_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncycle',
            name='planned_feed_bags',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre de sacs d'aliments planifiés (simulation)"),
        ),
    ]
