# Generated by Django 5.1.11 on 2026-04-18 00:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0013_add_planned_feed_bags_to_productioncycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialHarvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(blank=True, help_text='UUID généré côté mobile pour déduplication', null=True, unique=True, verbose_name='UUID client')),
                ('harvest_date', models.DateField(verbose_name='Date de récolte partielle')),
                ('count_harvested', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de poissons récoltés')),
                ('average_weight_g', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Poids moyen (g)')),
                ('total_weight_kg', models.DecimalField(decimal_places=3, help_text='Calculé automatiquement : count × poids / 1000', max_digits=10, verbose_name='Poids total récolté (kg)')),
                ('sale_price_fcfa_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Prix de vente (FCFA/kg)')),
                ('notes', models.CharField(blank=True, default='', max_length=500, verbose_name='Notes')),
                ('created_offline', models.BooleanField(default=False, verbose_name='Créé hors ligne')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synchronisé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_harvests', to='aquaculture.productioncycle', verbose_name='Cycle de production')),
            ],
            options={
                'verbose_name': 'Récolte partielle',
                'verbose_name_plural': 'Récoltes partielles',
                'ordering': ['-harvest_date', '-created_at'],
                'indexes': [models.Index(fields=['cycle', 'harvest_date'], name='aquaculture_cycle_i_c70f61_idx'), models.Index(fields=['client_uuid'], name='aquaculture_client__8744e8_idx'), models.Index(fields=['created_offline', 'synced_at'], name='aquaculture_created_cd7430_idx')],
            },
        ),
    ]
