# Generated by Django 5.1.11 on 2026-06-28 03:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_farmprofile_production_fields'),
        ('aquaculture', '0021_sync_delta_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Bac 1, Étang principal, Cage A', max_length=120, verbose_name="Nom de l'unité")),
                ('unit_type', models.CharField(choices=[('tank', 'Bac'), ('pond', 'Étang'), ('cage', 'Cage')], max_length=20, verbose_name="Type d'unité")),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Volume (m³)')),
                ('surface_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Surface (m²)')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('archived', 'Archivé')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_units', to='accounts.farmprofile', verbose_name='Profil de ferme')),
            ],
            options={
                'verbose_name': 'Unité de production',
                'verbose_name_plural': 'Unités de production',
                'db_table': 'aquaculture_production_unit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CycleUnitAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initial_fish_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Effectif initial')),
                ('current_fish_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Effectif actuel')),
                ('initial_biomass_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Biomasse initiale (kg)')),
                ('current_biomass_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Biomasse actuelle (kg)')),
                ('expected_survival_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taux de survie prévisionnel (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_allocations', to='aquaculture.productioncycle', verbose_name='Cycle de production')),
                ('production_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_allocations', to='aquaculture.productionunit', verbose_name='Unité de production')),
            ],
            options={
                'verbose_name': 'Allocation de cycle par unité',
                'verbose_name_plural': 'Allocations de cycle par unité',
                'db_table': 'aquaculture_cycle_unit_allocation',
                'ordering': ['cycle', 'production_unit__name'],
            },
        ),
        migrations.AddIndex(
            model_name='productionunit',
            index=models.Index(fields=['farm_profile', 'status'], name='aquaculture_farm_pr_835d70_idx'),
        ),
        migrations.AddIndex(
            model_name='productionunit',
            index=models.Index(fields=['farm_profile', 'unit_type'], name='aquaculture_farm_pr_73aeb5_idx'),
        ),
        migrations.AddIndex(
            model_name='cycleunitallocation',
            index=models.Index(fields=['cycle'], name='aquaculture_cycle_i_924503_idx'),
        ),
        migrations.AddIndex(
            model_name='cycleunitallocation',
            index=models.Index(fields=['production_unit'], name='aquaculture_product_1ef95c_idx'),
        ),
        migrations.AddConstraint(
            model_name='cycleunitallocation',
            constraint=models.UniqueConstraint(fields=('cycle', 'production_unit'), name='uniq_cycle_production_unit_allocation'),
        ),
    ]
