# Generated by Django 5.1.11 on 2026-06-28 04:20

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0022_productionunit_cycleunitallocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycleunitallocation',
            name='production_unit',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='cycle_allocations',
                to='aquaculture.productionunit',
                verbose_name='Unité de production',
            ),
        ),
    ]
