# Generated by Django 5.1.11 on 2026-06-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0023_alter_cycleunitallocation_production_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclelog',
            name='cycle_unit_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_logs', to='aquaculture.cycleunitallocation', verbose_name='Allocation de cycle par unité'),
        ),
        migrations.AddField(
            model_name='sanitarylog',
            name='cycle_unit_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanitary_logs', to='aquaculture.cycleunitallocation', verbose_name='Allocation de cycle par unité'),
        ),
    ]
