# Generated by Django 5.1.11 on 2026-06-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0024_add_cycle_unit_allocation_to_logs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cyclelog',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cyclelog',
            constraint=models.UniqueConstraint(condition=models.Q(('cycle_unit_allocation__isnull', True)), fields=('cycle', 'log_date'), name='uniq_cycle_log_global_per_day'),
        ),
        migrations.AddConstraint(
            model_name='cyclelog',
            constraint=models.UniqueConstraint(condition=models.Q(('cycle_unit_allocation__isnull', False)), fields=('cycle', 'cycle_unit_allocation', 'log_date'), name='uniq_cycle_unit_log_per_day'),
        ),
    ]
