# Generated by Django 5.1.11 on 2026-06-29 22:58

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0025_scope_cycle_logs_by_unit'),
        ('commerce', '0006_delete_aller_aqua_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleFeedStockEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(blank=True, help_text='UUID généré côté mobile pour déduplication', null=True, unique=True, verbose_name='UUID client')),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('order', 'Commande')], max_length=20, verbose_name='Source')),
                ('label', models.CharField(max_length=200, verbose_name="Nom de l'aliment")),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantité (kg)')),
                ('total_cost_fcfa', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant total (FCFA)')),
                ('entry_date', models.DateField(verbose_name="Date d'entrée")),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_offline', models.BooleanField(default=False, verbose_name='Créé hors ligne')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synchronisé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_stock_entries', to='aquaculture.productioncycle', verbose_name='Cycle de production')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_stock_entries', to='commerce.order', verbose_name='Commande')),
                ('order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_stock_entry', to='commerce.orderitem', verbose_name='Article de commande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_feed_stock_entries', to='commerce.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Entrée de stock du cycle',
                'verbose_name_plural': 'Entrées de stock du cycle',
                'db_table': 'aquaculture_cycle_feed_stock_entry',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['cycle', 'entry_date'], name='aq_feed_stock_cycle_date_idx'), models.Index(fields=['cycle', 'source'], name='aq_feed_stock_cycle_source_idx'), models.Index(fields=['client_uuid'], name='aquaculture_client__d790e7_idx'), models.Index(fields=['created_offline', 'synced_at'], name='aq_feed_stock_sync_idx')],
            },
        ),
    ]
