# Generated by Django 5.1.11 on 2026-06-30 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_farmprofile_production_fields'),
        ('aquaculture', '0026_cyclefeedstockentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionreport',
            name='uniq_report_period_per_farm',
        ),
        migrations.AddField(
            model_name='productionreport',
            name='scope_object_id',
            field=models.UUIDField(blank=True, help_text="UUID du cycle ou de l'allocation ciblée", null=True, verbose_name='UUID du contexte de rapport'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='scope_type',
            field=models.CharField(choices=[('cycle', 'Cycle'), ('unit', 'Unité')], default='cycle', help_text='Cycle ou unité de production ciblée', max_length=20, verbose_name='Portée du rapport'),
        ),
        migrations.AddIndex(
            model_name='productionreport',
            index=models.Index(fields=['scope_type', 'scope_object_id'], name='rpt_scope_type_object_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionreport',
            constraint=models.UniqueConstraint(fields=('farm_profile', 'report_type', 'period_start', 'period_end', 'scope_type', 'scope_object_id'), name='uniq_report_period_per_farm_scope'),
        ),
    ]
