# Generated by Django 5.1.11 on 2026-07-04 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0027_remove_productionreport_uniq_report_period_per_farm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedingplan',
            options={'ordering': ['cycle', 'cycle_unit_allocation', 'week_number'], 'verbose_name': "Plan d'alimentation", 'verbose_name_plural': "Plans d'alimentation"},
        ),
        migrations.AlterUniqueTogether(
            name='feedingplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feedingplan',
            name='cycle_unit_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feeding_plans', to='aquaculture.cycleunitallocation', verbose_name='Allocation de cycle par unité'),
        ),
        migrations.AddIndex(
            model_name='feedingplan',
            index=models.Index(fields=['cycle_unit_allocation', 'is_active', 'start_date', 'end_date'], name='aq_feed_unit_active_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedingplan',
            constraint=models.UniqueConstraint(condition=models.Q(('cycle_unit_allocation__isnull', False)), fields=('cycle_unit_allocation', 'week_number'), name='uniq_unit_feeding_plan_week'),
        ),
    ]
