# Generated by Django 5.1.11 on 2026-07-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0029_cycleunitallocation_harvest_fields_and_partialharvest_unit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partialharvest',
            new_name='aquaculture_cycle_u_cbe3a2_idx',
            old_name='aq_partial_unit_date_idx',
        ),
        migrations.AddField(
            model_name='cycleunitallocation',
            name='final_harvest_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date métier de récolte'),
        ),
        migrations.AddField(
            model_name='cycleunitallocation',
            name='final_harvest_notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes de récolte finale'),
        ),
    ]
