# Generated by Django 5.1.11 on 2026-07-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0030_rename_aq_partial_unit_date_idx_aquaculture_cycle_u_cbe3a2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleunitallocation',
            name='client_uuid',
            field=models.UUIDField(blank=True, help_text='UUID généré côté mobile ou dérivé du lancement pour déduplication', null=True, unique=True, verbose_name='UUID client'),
        ),
        migrations.AddField(
            model_name='productioncycle',
            name='launch_payload_hash',
            field=models.CharField(blank=True, editable=False, help_text='Empreinte SHA-256 du payload de lancement transactionnel', max_length=64, null=True, verbose_name='Empreinte du lancement'),
        ),
        migrations.AddField(
            model_name='productionunit',
            name='client_uuid',
            field=models.UUIDField(blank=True, help_text='UUID généré côté mobile ou dérivé du lancement pour déduplication', null=True, unique=True, verbose_name='UUID client'),
        ),
    ]
