# Generated by Django 5.1.11 on 2026-07-14 18:39

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('accounts', '0010_remove_farmprofile_production_fields'),
        ('aquaculture', '0031_cycleunitallocation_client_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="SET lock_timeout = '2s'",
            reverse_sql="RESET lock_timeout",
        ),
        migrations.CreateModel(
            name='CalibrationOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(unique=True)),
                ('calibrated_at', models.DateTimeField()),
                ('transferred_count', models.PositiveIntegerField()),
                ('transferred_average_weight_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transferred_biomass_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sample_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_total_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_category', models.CharField(blank=True, choices=[('small', 'Petit'), ('medium', 'Moyen'), ('large', 'Grand'), ('other', 'Autre')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('created_offline', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_count_before', models.PositiveIntegerField()),
                ('source_count_after', models.PositiveIntegerField()),
                ('source_average_weight_before_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('source_average_weight_after_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('source_biomass_before_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_biomass_after_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_count_before', models.PositiveIntegerField()),
                ('destination_count_after', models.PositiveIntegerField()),
                ('destination_average_weight_before_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('destination_average_weight_after_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('destination_biomass_before_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_biomass_after_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-calibrated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productioncycle',
            name='cycle_kind',
            field=models.CharField(choices=[('standard', 'Standard'), ('calibration', 'Calibration')], db_default='standard', default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='productionunit',
            name='created_offline',
            field=models.BooleanField(default=False, verbose_name='Créée hors ligne'),
        ),
        migrations.AddField(
            model_name='productionunit',
            name='purpose',
            field=models.CharField(choices=[('production', 'Production'), ('calibration', 'Calibration')], db_default='production', default='production', max_length=20, verbose_name="Usage de l'unité"),
        ),
        migrations.AddField(
            model_name='productionunit',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Synchronisée le'),
        ),
        AddIndexConcurrently(
            model_name='productionunit',
            index=models.Index(fields=['farm_profile', 'purpose', 'status'], name='aq_unit_farm_purpose_idx'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE UNIQUE INDEX CONCURRENTLY "uniq_active_allocation_per_unit" '
                        'ON "aquaculture_cycle_unit_allocation" ("production_unit_id") '
                        "WHERE \"status\" = 'active'"
                    ),
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "uniq_active_allocation_per_unit"',
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='cycleunitallocation',
                    constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('production_unit',), name='uniq_active_allocation_per_unit'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "aquaculture_production_unit" '
                        'ADD CONSTRAINT "unit_calibration_requires_tank_volume" CHECK '
                        "(\"purpose\" = 'production' OR (\"purpose\" = 'calibration' AND "
                        "\"surface_m2\" IS NULL AND \"unit_type\" = 'tank' AND \"volume_m3\" > 0)) NOT VALID"
                    ),
                    reverse_sql=(
                        'ALTER TABLE "aquaculture_production_unit" '
                        'DROP CONSTRAINT IF EXISTS "unit_calibration_requires_tank_volume"'
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "aquaculture_production_unit" '
                        'VALIDATE CONSTRAINT "unit_calibration_requires_tank_volume"'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='productionunit',
                    constraint=models.CheckConstraint(condition=models.Q(('purpose', 'production'), models.Q(('purpose', 'calibration'), ('surface_m2__isnull', True), ('unit_type', 'tank'), ('volume_m3__gt', 0)), _connector='OR'), name='unit_calibration_requires_tank_volume'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE UNIQUE INDEX CONCURRENTLY "uniq_calibration_unit_name_farm_ci" '
                        'ON "aquaculture_production_unit" '
                        "(LOWER(\"name\"), \"farm_profile_id\") WHERE \"purpose\" = 'calibration'"
                    ),
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "uniq_calibration_unit_name_farm_ci"',
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='productionunit',
                    constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('farm_profile'), condition=models.Q(('purpose', 'calibration')), name='uniq_calibration_unit_name_farm_ci'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='calibrationoperation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationoperation',
            name='destination_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_operations_in', to='aquaculture.cycleunitallocation'),
        ),
        migrations.AddField(
            model_name='calibrationoperation',
            name='source_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_operations_out', to='aquaculture.cycleunitallocation'),
        ),
        migrations.AddIndex(
            model_name='calibrationoperation',
            index=models.Index(fields=['source_allocation', 'calibrated_at'], name='aq_cal_op_source_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationoperation',
            index=models.Index(fields=['destination_allocation', 'calibrated_at'], name='aq_cal_op_dest_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationoperation',
            index=models.Index(fields=['client_uuid'], name='aq_cal_op_client_idx'),
        ),
        migrations.RunSQL(
            sql="RESET lock_timeout",
            reverse_sql="SET lock_timeout = '2s'",
        ),
    ]
