# Generated by Django 5.1.11 on 2026-07-14 16:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_farmprofile_production_fields'),
        ('aquaculture', '0031_cycleunitallocation_client_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncycle',
            name='unit_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('calibration', 'Bac de calibrage')], default='standard', max_length=20),
        ),
        migrations.CreateModel(
            name='CalibrationOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(unique=True)),
                ('calibrated_at', models.DateTimeField()),
                ('transferred_count', models.PositiveIntegerField()),
                ('transferred_average_weight_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transferred_biomass_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sample_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_total_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_category', models.CharField(blank=True, choices=[('small', 'Petit'), ('medium', 'Moyen'), ('large', 'Grand'), ('other', 'Autre')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('created_offline', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_count_before', models.PositiveIntegerField()),
                ('source_count_after', models.PositiveIntegerField()),
                ('source_average_weight_before_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('source_average_weight_after_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('source_biomass_before_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_biomass_after_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_count_before', models.PositiveIntegerField()),
                ('destination_count_after', models.PositiveIntegerField()),
                ('destination_average_weight_before_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('destination_average_weight_after_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('destination_biomass_before_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_biomass_after_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_operations_in', to='aquaculture.productioncycle')),
                ('source_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_operations_out', to='aquaculture.productioncycle')),
            ],
            options={
                'ordering': ['-calibrated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationTank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('volume_m3', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_offline', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_tanks', to='accounts.farmprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productioncycle',
            name='calibration_tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='aquaculture.calibrationtank'),
        ),
        migrations.AddConstraint(
            model_name='productioncycle',
            constraint=models.UniqueConstraint(condition=models.Q(('calibration_tank__isnull', False), ('status', 'active')), fields=('calibration_tank',), name='uniq_active_cycle_per_calibration_tank'),
        ),
        migrations.AddConstraint(
            model_name='productioncycle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('calibration_tank__isnull', True), ('unit_type', 'standard')), models.Q(('calibration_tank__isnull', False), ('unit_type', 'calibration')), _connector='OR'), name='cycle_calibration_tank_matches_type'),
        ),
        migrations.AddIndex(
            model_name='calibrationoperation',
            index=models.Index(fields=['source_cycle', 'calibrated_at'], name='aq_cal_op_source_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationoperation',
            index=models.Index(fields=['destination_cycle', 'calibrated_at'], name='aq_cal_op_dest_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationoperation',
            index=models.Index(fields=['client_uuid'], name='aq_cal_op_client_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationtank',
            index=models.Index(fields=['farm_profile', 'is_active'], name='aq_cal_tank_farm_active_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationtank',
            index=models.Index(fields=['client_uuid'], name='aq_cal_tank_client_idx'),
        ),
        migrations.AddConstraint(
            model_name='calibrationtank',
            constraint=models.UniqueConstraint(fields=('farm_profile', 'name'), name='uniq_calibration_tank_name_farm'),
        ),
        migrations.AddConstraint(
            model_name='calibrationtank',
            constraint=models.CheckConstraint(condition=models.Q(('volume_m3__gt', 0)), name='calibration_tank_volume_gt_zero'),
        ),
    ]
