# Generated by Django 5.1.11 on 2026-07-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0032_productioncycle_unit_type_calibrationoperation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationoperation',
            name='source_cycle_unit_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibration_operations_out', to='aquaculture.cycleunitallocation'),
        ),
    ]
