# Generated by Django 5.1.11 on 2026-07-15 05:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_postgresql_lock_timeout(apps, schema_editor):
    """Évite qu'une attente DDL ne bloque la file de connexions en production."""
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET LOCAL lock_timeout = '2s'")


class Migration(migrations.Migration):
    dependencies = [
        ("aquaculture", "0034_cycleunitallocation_final_harvested_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            set_postgresql_lock_timeout,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="FinalHarvestOperation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("client_uuid", models.UUIDField(unique=True)),
                ("harvested_at", models.DateTimeField()),
                ("declared_fish_count", models.PositiveIntegerField()),
                ("declared_average_weight_g", models.DecimalField(decimal_places=2, max_digits=8)),
                ("declared_biomass_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[("reconciled", "Réconciliée"), ("pending", "Réconciliation en attente")], max_length=20
                    ),
                ),
                ("computed_count_before_harvest", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "computed_biomass_before_harvest_kg",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("created_offline", models.BooleanField(default=False)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_harvest_operation",
                        to="aquaculture.cycleunitallocation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_harvest_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-harvested_at", "-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["harvested_at", "created_at"], name="aq_final_harvest_dates_idx"),
                    models.Index(fields=["reconciliation_status", "created_at"], name="aq_final_harvest_status_idx"),
                ],
            },
        ),
    ]
