# Generated by Django 5.1.11 on 2026-07-20 02:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


def normalize_name(value):
    return ' '.join((value or '').casefold().split())


def backfill_feed_references(apps, schema_editor):
    FeedReference = apps.get_model('aquaculture', 'FarmFeedReference')
    StockEntry = apps.get_model('aquaculture', 'CycleFeedStockEntry')
    CycleLog = apps.get_model('aquaculture', 'CycleLog')

    references = {}
    entries = StockEntry.objects.select_related('cycle', 'product').filter(feed_size_mm__isnull=False)
    for entry in entries.iterator():
        product = entry.product
        name = product.name if product else entry.label
        key = (entry.cycle.farm_profile_id, normalize_name(name), entry.cycle.species, entry.feed_size_mm)
        reference = references.get(key)
        if reference is None:
            reference, _ = FeedReference.objects.get_or_create(
                farm_profile_id=entry.cycle.farm_profile_id,
                normalized_name=key[1],
                species=entry.cycle.species,
                pellet_size_mm=entry.feed_size_mm,
                defaults={
                    'source': 'aquacare_catalog' if product else 'external',
                    'catalog_product_id': product.id if product else None,
                    'name': name.strip(),
                    'brand': product.brand if product else '',
                    'protein_percentage': product.protein_percentage if product else None,
                    'lipid_percentage': product.lipid_percentage if product else None,
                    'package_weight_kg': product.package_weight_kg if product else None,
                },
            )
            references[key] = reference
        StockEntry.objects.filter(pk=entry.pk).update(feed_reference_id=reference.id)

    logs = CycleLog.objects.select_related('cycle').filter(
        feed_quantity__isnull=False,
        feed_size_mm__isnull=False,
    )
    for log in logs.iterator():
        if not (log.feed_type or '').strip():
            continue
        key = (
            log.cycle.farm_profile_id,
            normalize_name(log.feed_type),
            log.cycle.species,
            log.feed_size_mm,
        )
        reference = references.get(key)
        if reference is None:
            reference, _ = FeedReference.objects.get_or_create(
                farm_profile_id=log.cycle.farm_profile_id,
                normalized_name=key[1],
                species=log.cycle.species,
                pellet_size_mm=log.feed_size_mm,
                defaults={
                    'source': 'external',
                    'name': (log.feed_type or '').strip(),
                },
            )
            references[key] = reference
        CycleLog.objects.filter(pk=log.pk).update(feed_reference_id=reference.id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_farmprofile_production_fields'),
        ('aquaculture', '0037_cyclefeedstockentry_feed_size_mm'),
        ('commerce', '0009_order_delivered_at_order_delivered_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmFeedReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID client')),
                ('source', models.CharField(choices=[('aquacare_catalog', 'Catalogue AquaCare'), ('external', 'Aliment externe')], max_length=24, verbose_name='Origine')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'aliment")),
                ('normalized_name', models.CharField(editable=False, max_length=200)),
                ('species', models.CharField(choices=[('tilapia', 'Tilapia'), ('clarias', 'Clarias (Silure)')], max_length=20, verbose_name='Espèce cible')),
                ('pellet_size_mm', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('20.0'))], verbose_name='Granulométrie (mm)')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('protein_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taux de protéines (%)')),
                ('lipid_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taux de lipides (%)')),
                ('package_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Poids du conditionnement (kg)')),
                ('created_offline', models.BooleanField(default=False, verbose_name='Créé hors ligne')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synchronisé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farm_feed_references', to='commerce.product', verbose_name='Produit AquaCare')),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_references', to='accounts.farmprofile', verbose_name='Ferme')),
            ],
            options={
                'verbose_name': 'Référence aliment de ferme',
                'verbose_name_plural': 'Références aliments de ferme',
                'db_table': 'aquaculture_farm_feed_reference',
                'ordering': ['name', 'pellet_size_mm'],
            },
        ),
        migrations.AddField(
            model_name='cyclefeedstockentry',
            name='feed_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='aquaculture.farmfeedreference', verbose_name='Référence aliment'),
        ),
        migrations.AddField(
            model_name='cyclelog',
            name='feed_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycle_logs', to='aquaculture.farmfeedreference', verbose_name='Référence aliment'),
        ),
        migrations.AddIndex(
            model_name='farmfeedreference',
            index=models.Index(fields=['farm_profile', 'species', 'pellet_size_mm'], name='aq_farm_feed_lookup_idx'),
        ),
        migrations.RunPython(backfill_feed_references, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='farmfeedreference',
            constraint=models.UniqueConstraint(fields=('farm_profile', 'normalized_name', 'species', 'pellet_size_mm'), name='aq_farm_feed_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='farmfeedreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('catalog_product__isnull', True), ('source', 'external')), models.Q(('catalog_product__isnull', False), ('source', 'aquacare_catalog')), _connector='OR'), name='aq_farm_feed_source_product_ck'),
        ),
    ]
