# Generated by Django 5.1.11 on 2026-07-20 02:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


def normalize_name(value):
    return ' '.join((value or '').casefold().split())


def backfill_feed_references(apps, schema_editor):
    FeedReference = apps.get_model('aquaculture', 'FarmFeedReference')
    StockEntry = apps.get_model('aquaculture', 'CycleFeedStockEntry')

    entries = StockEntry.objects.select_related(
        'cycle',
        'order_item',
        'order_item__order',
    ).filter(
        source='order',
        order_item__isnull=False,
    )
    for entry in entries.iterator():
        item = entry.order_item
        order = item.order
        species = 'clarias' if item.product_species_snapshot == 'catfish' else item.product_species_snapshot
        name = (item.product_name or '').strip()
        pellet_size = item.product_pellet_size_mm_snapshot
        package_weight = item.product_package_weight_kg_snapshot
        is_certain = all((
            order.production_cycle_id == entry.cycle_id,
            order.farm_profile_id == entry.cycle.farm_profile_id,
            name,
            species == entry.cycle.species,
            pellet_size is not None,
            package_weight is not None and package_weight > 0,
        ))
        if not is_certain:
            continue
        reference, _ = FeedReference.objects.get_or_create(
            farm_profile_id=entry.cycle.farm_profile_id,
            source='aquacare_catalog',
            catalog_product_id=item.product_id,
            normalized_name=normalize_name(name),
            species=species,
            pellet_size_mm=pellet_size,
            defaults={
                'name': name,
                'brand': item.product_brand_snapshot or '',
                'package_weight_kg': package_weight,
            },
        )
        StockEntry.objects.filter(pk=entry.pk).update(feed_reference_id=reference.id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_farmprofile_production_fields'),
        ('aquaculture', '0037_cyclefeedstockentry_feed_size_mm'),
        ('commerce', '0009_order_delivered_at_order_delivered_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmFeedReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID client')),
                ('source', models.CharField(choices=[('aquacare_catalog', 'Catalogue AquaCare'), ('external', 'Aliment externe')], max_length=24, verbose_name='Origine')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'aliment")),
                ('normalized_name', models.CharField(editable=False, max_length=200)),
                ('species', models.CharField(choices=[('tilapia', 'Tilapia'), ('clarias', 'Clarias (Silure)')], max_length=20, verbose_name='Espèce cible')),
                ('pellet_size_mm', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('20.0'))], verbose_name='Granulométrie (mm)')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('protein_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taux de protéines (%)')),
                ('lipid_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taux de lipides (%)')),
                ('package_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Poids du conditionnement (kg)')),
                ('created_offline', models.BooleanField(default=False, verbose_name='Créé hors ligne')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synchronisé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farm_feed_references', to='commerce.product', verbose_name='Produit AquaCare')),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_references', to='accounts.farmprofile', verbose_name='Ferme')),
            ],
            options={
                'verbose_name': 'Référence aliment de ferme',
                'verbose_name_plural': 'Références aliments de ferme',
                'db_table': 'aquaculture_farm_feed_reference',
                'ordering': ['name', 'pellet_size_mm'],
            },
        ),
        migrations.AddField(
            model_name='cyclefeedstockentry',
            name='feed_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='aquaculture.farmfeedreference', verbose_name='Référence aliment'),
        ),
        migrations.AddField(
            model_name='cyclelog',
            name='feed_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycle_logs', to='aquaculture.farmfeedreference', verbose_name='Référence aliment'),
        ),
        migrations.AddIndex(
            model_name='farmfeedreference',
            index=models.Index(fields=['farm_profile', 'species', 'pellet_size_mm'], name='aq_farm_feed_lookup_idx'),
        ),
        # Le forward ne supprime ni ne réécrit les snapshots : il rattache uniquement
        # les entrées certaines. Au rollback, les FK sont supprimées par les
        # opérations inverses, donc aucun reverse de données supplémentaire n'est
        # nécessaire.
        migrations.RunPython(backfill_feed_references, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='farmfeedreference',
            constraint=models.UniqueConstraint(fields=('farm_profile', 'normalized_name', 'species', 'pellet_size_mm'), name='aq_farm_feed_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='farmfeedreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('catalog_product__isnull', True), ('source', 'external')), models.Q(('catalog_product__isnull', False), ('source', 'aquacare_catalog')), _connector='OR'), name='aq_farm_feed_source_product_ck'),
        ),
    ]
