# Generated by Django 5.1.11 on 2026-07-20 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0038_farm_feed_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleFeedPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(default=2, verbose_name='Version')),
                ('parameters', models.JSONField(default=dict, verbose_name='Paramètres de simulation')),
                ('phases', models.JSONField(default=list, verbose_name='Phases alimentaires')),
                ('total_feed_kg', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Aliment total planifié (kg)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculé le')),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feed_plan_snapshot', to='aquaculture.productioncycle', verbose_name='Cycle de production')),
            ],
            options={
                'verbose_name': 'Plan alimentaire du cycle',
                'verbose_name_plural': 'Plans alimentaires des cycles',
                'db_table': 'aquaculture_cycle_feed_plan',
            },
        ),
    ]
