# Generated by Django 5.1.11 on 2026-07-20

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0039_cycle_feed_plan'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='farmfeedreference',
            name='aq_farm_feed_identity_uniq',
        ),
        migrations.AddConstraint(
            model_name='farmfeedreference',
            constraint=models.UniqueConstraint(
                condition=models.Q(source='external'),
                fields=('farm_profile', 'normalized_name', 'species', 'pellet_size_mm'),
                name='aq_external_feed_identity_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='farmfeedreference',
            constraint=models.UniqueConstraint(
                condition=models.Q(source='aquacare_catalog'),
                fields=(
                    'farm_profile',
                    'catalog_product',
                    'normalized_name',
                    'species',
                    'pellet_size_mm',
                ),
                name='aq_catalog_feed_identity_uniq',
            ),
        ),
        migrations.CreateModel(
            name='CycleFeedStockAdjustment',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'quantity_kg',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
                        verbose_name='Quantité déjà consommée (kg)',
                    ),
                ),
                (
                    'reason',
                    models.CharField(
                        default='legacy_consumption',
                        editable=False,
                        max_length=32,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'stock_entry',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='historical_adjustment',
                        to='aquaculture.cyclefeedstockentry',
                        verbose_name='Entrée de stock',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ajustement historique du stock',
                'verbose_name_plural': 'Ajustements historiques du stock',
                'db_table': 'aquaculture_cycle_feed_stock_adjustment',
            },
        ),
    ]
