# Generated by Django 5.1.11 on 2026-07-28

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def backfill_tracking_baselines_and_stock_metadata(apps, schema_editor):
    ProductionCycle = apps.get_model('aquaculture', 'ProductionCycle')
    CycleFeedStockEntry = apps.get_model('aquaculture', 'CycleFeedStockEntry')

    batch_size = 1000
    while True:
        cycle_ids = list(
            ProductionCycle.objects.filter(tracking_start_date__isnull=True)
            .values_list('pk', flat=True)[:batch_size]
        )
        if not cycle_ids:
            break
        cycles = ProductionCycle.objects.filter(pk__in=cycle_ids).only(
            'pk',
            'start_date',
            'initial_count',
            'initial_average_weight',
            'initial_biomass',
        )
        for cycle in cycles:
            cycle.onboarding_mode = 'new'
            cycle.tracking_start_date = cycle.start_date
            cycle.tracking_start_count = cycle.initial_count
            cycle.tracking_start_average_weight = cycle.initial_average_weight
            cycle.tracking_start_biomass = cycle.initial_biomass
            cycle.tracking_start_biomass_source = 'calculated'
        ProductionCycle.objects.bulk_update(
            cycles,
            [
                'onboarding_mode',
                'tracking_start_date',
                'tracking_start_count',
                'tracking_start_average_weight',
                'tracking_start_biomass',
                'tracking_start_biomass_source',
            ],
            batch_size=batch_size,
        )

    CycleFeedStockEntry.objects.filter(source='manual').update(
        entry_kind='manual_supply',
        cost_status='known',
    )
    CycleFeedStockEntry.objects.filter(source='order').update(
        entry_kind='order_receipt',
        cost_status='known',
    )


class Migration(migrations.Migration):
    dependencies = [
        ('aquaculture', '0046_add_aquacare_starter_nutritional_guides'),
    ]

    operations = [
        migrations.RunSQL(
            sql="SET LOCAL lock_timeout = '2s';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='productioncycle',
            name='onboarding_mode',
            field=models.CharField(
                choices=[('new', 'Nouveau cycle'), ('ongoing', 'Cycle déjà en cours')],
                db_default='new',
                default='new',
                max_length=16,
                verbose_name="Mode d'entrée dans le suivi",
            ),
        ),
        migrations.AddField(
            model_name='productioncycle',
            name='tracking_start_date',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Date de démarrage du suivi AquaCare',
            ),
        ),
        migrations.AddField(
            model_name='productioncycle',
            name='tracking_start_count',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000000),
                ],
                verbose_name='Effectif au démarrage du suivi',
            ),
        ),
        migrations.AddField(
            model_name='productioncycle',
            name='tracking_start_average_weight',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('0.1'))],
                verbose_name='Poids moyen au démarrage du suivi (g)',
            ),
        ),
        migrations.AddField(
            model_name='productioncycle',
            name='tracking_start_biomass',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
                verbose_name='Biomasse au démarrage du suivi (kg)',
            ),
        ),
        migrations.AddField(
            model_name='productioncycle',
            name='tracking_start_biomass_source',
            field=models.CharField(
                choices=[('calculated', 'Calculée'), ('declared', 'Déclarée')],
                db_default='calculated',
                default='calculated',
                max_length=16,
                verbose_name='Source de la biomasse au démarrage du suivi',
            ),
        ),
        migrations.AlterField(
            model_name='productioncycle',
            name='initial_average_weight',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='8-15g typiquement pour alevins',
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('0.1'))],
                verbose_name='Poids moyen initial (g)',
            ),
        ),
        migrations.AlterField(
            model_name='productioncycle',
            name='initial_biomass',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Calculé automatiquement',
                max_digits=10,
                null=True,
                verbose_name='Biomasse initiale (kg)',
            ),
        ),
        migrations.AddField(
            model_name='cyclefeedstockentry',
            name='entry_kind',
            field=models.CharField(
                choices=[
                    ('opening_balance', "Solde d'ouverture"),
                    ('manual_supply', 'Approvisionnement manuel'),
                    ('order_receipt', 'Réception de commande'),
                ],
                db_default='manual_supply',
                default='manual_supply',
                max_length=24,
                verbose_name="Type d'entrée",
            ),
        ),
        migrations.AddField(
            model_name='cyclefeedstockentry',
            name='cost_status',
            field=models.CharField(
                choices=[('known', 'Coût connu'), ('unknown', 'Coût inconnu')],
                db_default='known',
                default='known',
                max_length=12,
                verbose_name='Statut du coût',
            ),
        ),
        migrations.AlterField(
            model_name='cyclefeedstockentry',
            name='total_cost_fcfa',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                db_default=Decimal('0'),
                default=Decimal('0'),
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                verbose_name='Montant total (FCFA)',
            ),
        ),
        migrations.RunPython(
            backfill_tracking_baselines_and_stock_metadata,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
