# Generated by Django 5.2.17 on 2026-10-03 11:41

import common.protected_media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaculture", "0052_remove_automatic_report_schedules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionreport",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=common.protected_media.RandomizedUploadPath(
                    "reports/%Y/%m", ("pdf",)
                ),
                verbose_name="Fichier PDF",
            ),
        ),
        migrations.AlterField(
            model_name="sanitarylog",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Compressée automatiquement côté mobile",
                null=True,
                upload_to=common.protected_media.RandomizedUploadPath(
                    "sanitary_logs/%Y/%m", ("jpg", "jpeg", "png", "webp")
                ),
                verbose_name="Photo",
            ),
        ),
    ]
