# Generated by Django 5.1.11 on 2025-08-25 14:34

import accounts.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(help_text='Format : +237XXXXXXXXX ou format international', max_length=20, unique=True, validators=[accounts.validators.validate_cameroon_phone], verbose_name='Numéro de téléphone')),
                ('account_type', models.CharField(choices=[('individual', 'Personne physique'), ('company', 'Entreprise')], default='individual', help_text="Type d'utilisateur : personne physique ou entreprise", max_length=20, verbose_name='Type de compte')),
                ('business_name', models.CharField(blank=True, help_text='Nom de l\'entreprise pour les comptes de type "company"', max_length=200, null=True, verbose_name="Nom de l'entreprise")),
                ('is_verified', models.BooleanField(default=False, help_text='Indique si le numéro de téléphone a été vérifié par SMS', verbose_name='Téléphone vérifié')),
                ('language_preference', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', help_text="Langue d'interface préférée de l'utilisateur", max_length=5, verbose_name='Langue préférée')),
                ('activity_type', models.CharField(blank=True, choices=[('alevins', "Producteur d'alevins"), ('poisson_table', 'Producteur de poisson de table'), ('mixte', 'Production mixte (alevins et poisson de table)')], help_text="Maillon d'activité : producteur d'alevins, poisson de table, etc.", max_length=20, null=True, verbose_name="Type d'activité")),
                ('region', models.CharField(blank=True, choices=[('adamaoua', 'Adamaoua'), ('centre', 'Centre'), ('est', 'Est'), ('extreme_nord', 'Extrême-Nord'), ('littoral', 'Littoral'), ('nord', 'Nord'), ('nord_ouest', 'Nord-Ouest'), ('ouest', 'Ouest'), ('sud', 'Sud'), ('sud_ouest', 'Sud-Ouest')], help_text='Région du Cameroun', max_length=20, null=True, verbose_name='Région')),
                ('department', models.CharField(blank=True, help_text='Département dans la région choisie', max_length=50, null=True, verbose_name='Département')),
                ('district', models.CharField(blank=True, help_text='Arrondissement dans le département', max_length=100, null=True, verbose_name='Arrondissement')),
                ('neighborhood', models.CharField(blank=True, help_text='Quartier ou localité spécifique', max_length=100, null=True, verbose_name='Quartier')),
                ('legal_status', models.CharField(blank=True, choices=[('ei', 'Entreprise Individuelle (EI)'), ('scoop', 'Coopérative Simplifiée (SCOOP)'), ('coop_ca', "Coopérative avec Conseil d'Administration (Coop-CA)"), ('sarl', 'Société à Responsabilité Limitée (SARL)'), ('sarlu', 'SARL Unipersonnelle (SARLU)'), ('sa', 'Société Anonyme (SA)'), ('sas', 'Société par Actions Simplifiée (SAS)'), ('sasu', 'SAS Unipersonnelle (SASU)'), ('snc', 'Société en Nom Collectif (SNC)'), ('scs', 'Société en Commandite Simple (SCS)'), ('sci', 'Société Civile Immobilière (SCI)'), ('autre', 'Autre statut juridique')], help_text="Statut juridique de l'entreprise (SARL, SCOOP, etc.)", max_length=20, null=True, verbose_name='Statut juridique')),
                ('promoter_name', models.CharField(blank=True, help_text="Nom du promoteur ou dirigeant de l'entreprise", max_length=200, null=True, verbose_name='Nom du promoteur')),
                ('age_group', models.CharField(blank=True, choices=[('18_25', '18-25 ans'), ('26_35', '26-35 ans'), ('36_45', '36-45 ans'), ('46_55', '46-55 ans'), ('56_65', '56-65 ans'), ('65_plus', '65 ans et plus')], help_text="Tranche d'âge de la personne", max_length=10, null=True, verbose_name="Classe d'âge")),
                ('intervention_zone', models.CharField(blank=True, help_text="Zone géographique d'intervention de l'activité", max_length=200, null=True, verbose_name="Zone d'intervention")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur AquaCare',
                'verbose_name_plural': 'Utilisateurs AquaCare',
                'db_table': 'accounts_user',
            },
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique UUID pour la synchronisation mobile', primary_key=True, serialize=False)),
                ('farm_name', models.CharField(help_text="Nom commercial ou descriptif de l'exploitation", max_length=200, verbose_name='Nom de la ferme')),
                ('certification_status', models.CharField(choices=[('pending', 'En attente'), ('certified', 'Certifiée'), ('suspended', 'Suspendue'), ('rejected', 'Rejetée')], default='pending', help_text='Statut de certification géré uniquement par les admins AquaCare', max_length=20, verbose_name='Statut de certification')),
                ('total_ponds', models.PositiveIntegerField(default=0, help_text="Nombre total de bassins d'élevage disponibles", verbose_name='Nombre total de bassins')),
                ('total_area_m2', models.DecimalField(blank=True, decimal_places=2, help_text="Superficie totale de l'exploitation en mètres carrés", max_digits=10, null=True, verbose_name='Superficie totale (m²)')),
                ('water_source', models.CharField(blank=True, help_text="Principale source d'approvisionnement en eau", max_length=100, verbose_name="Source d'eau")),
                ('main_species', models.CharField(blank=True, help_text='Principale espèce de poisson élevée', max_length=100, verbose_name='Espèce principale')),
                ('annual_production_kg', models.PositiveIntegerField(blank=True, help_text='Production annuelle estimée en kilogrammes', null=True, verbose_name='Production annuelle (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création automatique du profil', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification du profil', verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(default=False, help_text='Marqueur de suppression pour la synchronisation mobile', verbose_name='Supprimé')),
                ('user', models.OneToOneField(help_text='Utilisateur propriétaire de cette ferme', on_delete=django.db.models.deletion.CASCADE, related_name='farm_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil de ferme',
                'verbose_name_plural': 'Profils de fermes',
                'db_table': 'accounts_farm_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
