# Generated by Django 5.1.11 on 2025-09-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('alevins', "Producteur d'alevins"), ('poisson_table', 'Producteur de poisson de table'), ('mixte', 'Production mixte (alevins et poisson de table)'), ('commercant', 'Commerçant de poisson')], help_text="Maillon d'activité : producteur d'alevins, poisson de table, etc.", max_length=20, null=True, verbose_name="Type d'activité"),
        ),
    ]
