# Generated by Django 5.1.11 on 2025-09-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text="Ville dans l'arrondissement", max_length=100, null=True, verbose_name='Ville'),
        ),
    ]
