# Generated by Django 5.1.11 on 2025-10-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_city_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmprofile',
            name='default_feed_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=500, help_text="Prix unitaire de l'aliment en FCFA par kg (utilisé pour calcul coûts)", max_digits=8, verbose_name='Prix aliment par défaut (FCFA/kg)'),
        ),
    ]
