# Generated by Django 5.1.11 on 2026-03-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_default_feed_price'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='farmprofile',
            index=models.Index(fields=['certification_status'], name='idx_farm_certification'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_type'], name='idx_user_account_type'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['region'], name='idx_user_region'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_type', 'business_name'], name='idx_user_company_login'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_type', 'first_name', 'last_name'], name='idx_user_person_login'),
        ),
    ]
