# Generated by Django 5.1.11 on 2026-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_farmprofile_add_gps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='annual_production_target_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Objectif de production annuelle en kg (utilisé pour la simulation)', max_digits=10, null=True, verbose_name='Production cible annuelle (kg)'),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='farm_setup_completed',
            field=models.BooleanField(default=False, help_text='True quand l\'utilisateur a terminé le flux "Créer mon élevage"', verbose_name='Configuration élevage complétée'),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='fingerlings_cost_per_unit_fcfa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix unitaire d'un alevin en FCFA", max_digits=10, null=True, verbose_name='Coût par alevin (FCFA)'),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='num_cycles_per_year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, '2 cycles par an'), (3, '3 cycles par an')], help_text='2 ou 3 cycles par an, selon le choix lors de la simulation', null=True, verbose_name='Nombre de cycles par an'),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='planned_selling_price_per_kg_fcfa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente prévu du poisson en FCFA/kg', max_digits=10, null=True, verbose_name='Prix de vente estimé (FCFA/kg)'),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='setup_infrastructure_type',
            field=models.CharField(blank=True, choices=[('etang', 'Étang'), ('cage_flottante', 'Cage flottante'), ('bac_hors_sol', 'Bac hors sol'), ('bac_en_sol', 'Bac en sol')], help_text="Type principal d'infrastructure d'élevage", max_length=30, verbose_name="Type d'infrastructure"),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='setup_species',
            field=models.CharField(blank=True, choices=[('tilapia', 'Tilapia'), ('clarias', 'Silure (Clarias)'), ('autre', 'Autre espèce')], help_text="Espèce choisie lors du flux de création d'élevage", max_length=20, verbose_name='Espèce principale (setup)'),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='setup_unit_count',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de bacs, étangs ou cages', null=True, verbose_name="Nombre d'unités (bacs/étangs)"),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='setup_unit_surface_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface de chaque étang en m²', max_digits=8, null=True, verbose_name='Surface par unité (m²)'),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='setup_unit_volume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume de chaque bac ou cage en m³', max_digits=8, null=True, verbose_name='Volume par unité (m³)'),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='certification_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('certified', 'Certifiée'), ('suspended', 'Suspendue'), ('rejected', 'Rejetée')], default='pending', help_text='Statut de certification géré par les administrateurs', max_length=20, verbose_name='Statut de certification'),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='default_feed_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=1250, help_text="Prix unitaire de l'aliment en FCFA par kg (utilisé pour calcul coûts)", max_digits=8, verbose_name='Prix aliment par défaut (FCFA/kg)'),
        ),
    ]
