# Generated by Django 5.2.17 on 2026-09-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_farmprofile_production_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmprofile',
            name='location_captured_at',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière capture de la position (ne change pas avec les autres champs)', null=True, verbose_name='Position GPS enregistrée le'),
        ),
    ]
