# Generated by Django 5.2.17 on 2026-09-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_farm_location_captured_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ferme', 'verbose_name_plural': 'Fermes'},
        ),
    ]
