# Generated by Django 5.2.8 on 2025-11-10 11:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_add_default_feed_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique UUID pour synchronisation mobile', primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(blank=True, help_text='UUID généré côté mobile pour déduplication lors de la sync', null=True, unique=True, verbose_name='UUID client')),
                ('order_number', models.CharField(help_text='Format: ORD-YYYYMMDD-XXXX (généré automatiquement)', max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmée')], default='confirmed', help_text='Statut de la commande', max_length=20, verbose_name='Statut')),
                ('delivery_method', models.CharField(choices=[('home', 'Livraison à domicile'), ('pickup', 'Retrait en magasin')], help_text='Livraison à domicile ou retrait en magasin', max_length=20, verbose_name='Mode de livraison')),
                ('pickup_location', models.CharField(blank=True, choices=[('ndokoti', 'Marché Ndokoti'), ('ndogpasi', 'Marché Ndogpasi')], help_text='Marché Ndokoti ou Ndogpasi (si retrait)', max_length=50, verbose_name='Point de retrait')),
                ('delivery_name', models.CharField(help_text='Nom complet du destinataire', max_length=200, verbose_name='Nom destinataire')),
                ('delivery_phone', models.CharField(help_text='Numéro de téléphone pour contact livraison', max_length=20, verbose_name='Téléphone destinataire')),
                ('delivery_region', models.CharField(help_text='Région Cameroun (ex: Littoral, Centre)', max_length=50, verbose_name='Région')),
                ('delivery_city', models.CharField(help_text='Ville de livraison', max_length=100, verbose_name='Ville')),
                ('delivery_full_address', models.TextField(help_text='Adresse complète de livraison (région, département, ville, quartier)', verbose_name='Adresse complète')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Somme des articles avant frais de livraison', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sous-total (FCFA)')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Frais de livraison calculés automatiquement', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frais de livraison (FCFA)')),
                ('total', models.DecimalField(decimal_places=2, help_text='Montant total = sous-total + frais de livraison', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total (FCFA)')),
                ('created_offline', models.BooleanField(default=False, help_text='True si commande créée en mode offline mobile', verbose_name='Créée hors ligne')),
                ('synced_at', models.DateTimeField(blank=True, help_text='Date/heure de synchronisation avec le serveur', null=True, verbose_name='Synchronisée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('farm_profile', models.ForeignKey(help_text='Ferme associée à la commande', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.farmprofile', verbose_name='Ferme')),
                ('user', models.ForeignKey(help_text='Aquaculteur ayant passé la commande', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique UUID pour synchronisation mobile', primary_key=True, serialize=False)),
                ('brand', models.CharField(choices=[('aller_aqua', 'Aller Aqua'), ('dibaq', 'DIBAQ')], help_text="Marque de l'aliment", max_length=50, verbose_name='Marque')),
                ('name', models.CharField(help_text='Ex: CLARIAS FLOAT 3MM, TIL-PRO SANA 2MM', max_length=200, verbose_name='Nom commercial')),
                ('species', models.CharField(choices=[('tilapia', 'Tilapia'), ('catfish', 'Silure (Catfish)')], help_text='Espèce de poisson visée', max_length=20, verbose_name='Espèce cible')),
                ('phase', models.CharField(choices=[('alevinage', 'Alevinage'), ('pre_grossissement', 'Pré-grossissement'), ('grossissement', 'Grossissement')], help_text='Phase de croissance du poisson', max_length=30, verbose_name="Phase d'élevage")),
                ('pellet_size_mm', models.DecimalField(decimal_places=2, help_text='Diamètre du granulé en millimètres', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Taille granulé (mm)')),
                ('protein_percentage', models.PositiveIntegerField(help_text='Pourcentage de protéines brutes', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Taux de protéines (%)')),
                ('lipid_percentage', models.PositiveIntegerField(help_text='Pourcentage de matières grasses', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Taux de lipides (%)')),
                ('package_weight_kg', models.PositiveIntegerField(help_text="Poids d'un sac (15, 20 ou 25 kg selon produit)", verbose_name='Poids conditionnement (kg)')),
                ('price_per_package', models.DecimalField(decimal_places=2, help_text="Prix unitaire d'un sac en Francs CFA", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix par sac (FCFA)')),
                ('is_available', models.BooleanField(default=True, help_text='Si False, produit retiré temporairement du catalogue', verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['species', 'phase', 'pellet_size_mm'],
                'indexes': [models.Index(fields=['species', 'phase'], name='commerce_pr_species_7ad7bd_idx'), models.Index(fields=['brand', 'is_available'], name='commerce_pr_brand_ea86d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Nom du produit au moment de la commande', max_length=200, verbose_name='Nom produit')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix du sac au moment de la commande', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix unitaire (FCFA)')),
                ('quantity', models.PositiveIntegerField(help_text='Nombre de sacs commandés', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total de la ligne = prix unitaire × quantité', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total ligne (FCFA)')),
                ('order', models.ForeignKey(help_text='Commande parente', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order', verbose_name='Commande')),
                ('product', models.ForeignKey(help_text='Référence produit (lien vers catalogue)', on_delete=django.db.models.deletion.PROTECT, to='commerce.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article commande',
                'verbose_name_plural': 'Articles commande',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='commerce_or_user_id_811790_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='commerce_or_order_n_8308f7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_uuid'], name='commerce_or_client__4ea16e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_offline', 'synced_at'], name='commerce_or_created_bd6f9f_idx'),
        ),
    ]
