# Generated by Django 5.1.11 on 2025-11-17 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lipid_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Pourcentage de matières grasses (optionnel si non-vérifié)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Taux de lipides (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='phase',
            field=models.CharField(blank=True, choices=[('alevinage', 'Alevinage'), ('pre_grossissement', 'Pré-grossissement'), ('grossissement', 'Grossissement')], help_text='Phase de croissance du poisson (optionnel si non-vérifié)', max_length=30, null=True, verbose_name="Phase d'élevage"),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Pourcentage de protéines brutes (optionnel si non-vérifié)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Taux de protéines (%)'),
        ),
    ]
