# Generated by Django 5.1.11 on 2026-03-30 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0012_order_production_cycle_fk'),
        ('commerce', '0004_extend_order_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='production_cycle',
            field=models.ForeignKey(blank=True, help_text='Cycle de production pour lequel cette commande est passée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='aquaculture.productioncycle', verbose_name='Cycle de production'),
        ),
        migrations.AlterField(
            model_name='product',
            name='phase',
            field=models.CharField(blank=True, choices=[('alevinage', 'Alevinage'), ('pre_grossissement', 'Pré-grossissement'), ('grossissement', 'Grossissement'), ('larvae', 'Larves'), ('juvenile', 'Juvénile'), ('growing', 'Croissance'), ('fattening', 'Engraissement'), ('finishing', 'Finition')], help_text='Phase de croissance du poisson (optionnel si non-vérifié)', max_length=30, null=True, verbose_name="Phase d'élevage"),
        ),
        migrations.AlterField(
            model_name='product',
            name='species',
            field=models.CharField(choices=[('tilapia', 'Tilapia'), ('catfish', 'Silure (Catfish)'), ('mixed', 'Mixte (Tilapia + Catfish)')], help_text='Espèce de poisson visée', max_length=20, verbose_name='Espèce cible'),
        ),
    ]
