# Generated by Django 5.1.11 on 2026-06-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_delete_aller_aqua_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('dibaq', 'DIBAQ')], help_text="Marque de l'aliment", max_length=50, verbose_name='Marque'),
        ),
    ]
