# Generated by Django 5.1.11 on 2026-07-18 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_order_fulfilment_workflow(apps, schema_editor):
    """Normalise le retrait historique et conserve le meilleur timestamp disponible.

    Avant cette migration, ``updated_at`` est le seul horodatage du dernier changement
    d'une commande. Il constitue donc le fallback documenté le plus fiable, sans
    inventer d'opérateur historique.
    """
    Order = apps.get_model('commerce', 'Order')
    Order.objects.filter(
        delivery_method='pickup',
        status='delivered',
    ).update(
        status='ready_for_pickup',
        ready_for_pickup_at=models.F('updated_at'),
    )
    Order.objects.filter(
        delivery_method='home',
        status='delivered',
    ).update(delivered_at=models.F('updated_at'))
    Order.objects.filter(status='received').update(received_at=models.F('updated_at'))


def restore_legacy_pickup_status(apps, schema_editor):
    Order = apps.get_model('commerce', 'Order')
    Order.objects.filter(
        delivery_method='pickup',
        status='ready_for_pickup',
    ).update(status='delivered')


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_order_document_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={
                'ordering': ['order', 'id'],
                'verbose_name': 'Article commandé',
                'verbose_name_plural': 'Articles commandés',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle la livraison à domicile a été déclarée', null=True, verbose_name='Livrée le'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_by',
            field=models.ForeignKey(blank=True, help_text='Opérateur ayant déclaré la livraison à domicile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_marked_delivered', to=settings.AUTH_USER_MODEL, verbose_name='Livrée par'),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_for_pickup_at',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle la commande a été déclarée prête au retrait', null=True, verbose_name='Prête au retrait le'),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_for_pickup_by',
            field=models.ForeignKey(blank=True, help_text='Opérateur ayant déclaré la commande prête au retrait', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_marked_ready_for_pickup', to=settings.AUTH_USER_MODEL, verbose_name='Prête au retrait par'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le client a confirmé la réception ou le retrait', null=True, verbose_name='Réception confirmée le'),
        ),
        migrations.RunPython(
            backfill_order_fulfilment_workflow,
            restore_legacy_pickup_status,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Commandée'), ('delivered', 'Livrée — confirmation attendue'), ('ready_for_pickup', 'Prête au retrait'), ('received', 'Réception confirmée')], default='confirmed', help_text='Statut de la commande', max_length=20, verbose_name='Statut'),
        ),
    ]
