# Generated by Django 5.2.17 on 2026-09-30 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_order_delivered_at_order_delivered_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name="Motif d'annulation"),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_source',
            field=models.CharField(blank=True, choices=[('customer', 'Client'), ('operator', 'Équipe AquaCare')], default='', max_length=20, verbose_name="Origine de l'annulation"),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Annulée le'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Annulée par'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Commandée'), ('delivered', 'Livrée — confirmation attendue'), ('ready_for_pickup', 'Prête au retrait'), ('received', 'Réception confirmée'), ('cancelled', 'Annulée')], default='confirmed', help_text='Statut de la commande', max_length=20, verbose_name='Statut'),
        ),
    ]
