import React from 'react';
import { ActivityIndicator, StyleSheet, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { AppText } from './AppText';
import { Button } from './Button';
import { Card } from './Card';
import { colors, spacing } from '@/theme';
interface StateProps { title?: string; message?: string; actionLabel?: string; onAction?: () => void; compact?: boolean; }
export function LoadingState({ message, compact = false }: Pick<StateProps, 'message' | 'compact'>) { return <View style={[styles.state, compact && styles.compact]}><ActivityIndicator color={colors.brand.primary} />{message ? <AppText color="muted">{message}</AppText> : null}</View>; }
export function EmptyState({ title, message, actionLabel, onAction, compact }: StateProps) { return <View style={[styles.state, compact && styles.compact]}><Ionicons name="file-tray-outline" size={36} color={colors.text.muted} />{title ? <AppText variant="cardTitle">{title}</AppText> : null}{message ? <AppText color="muted" style={styles.center}>{message}</AppText> : null}{actionLabel && onAction ? <Button label={actionLabel} onPress={onAction} fullWidth={false} /> : null}</View>; }
export function ErrorState({ title, message, actionLabel, onAction, compact }: StateProps) { return <View style={[styles.state, compact && styles.compact]}><Ionicons name="alert-circle-outline" size={36} color={colors.status.error} />{title ? <AppText variant="cardTitle">{title}</AppText> : null}{message ? <AppText color="muted" style={styles.center}>{message}</AppText> : null}{actionLabel && onAction ? <Button label={actionLabel} onPress={onAction} variant="outline" fullWidth={false} /> : null}</View>; }
export function InlineAlert({ tone = 'info', title, message }: Pick<StateProps, 'title' | 'message'> & { tone?: 'info' | 'success' | 'warning' | 'error' }) { const backgrounds = { info: colors.status.infoSurface, success: colors.status.successSurface, warning: colors.status.warningSurface, error: colors.status.errorSurface }; const icon = { info: 'information-circle-outline', success: 'checkmark-circle-outline', warning: 'warning-outline', error: 'alert-circle-outline' } as const; return <Card style={[styles.alert, { backgroundColor: backgrounds[tone] }]}><View style={styles.alertRow}><Ionicons name={icon[tone]} size={20} color={colors.status[tone]} /><View style={styles.alertText}>{title ? <AppText variant="label">{title}</AppText> : null}{message ? <AppText variant="helper">{message}</AppText> : null}</View></View></Card>; }
const styles = StyleSheet.create({ state: { minHeight: 200, alignItems: 'center', justifyContent: 'center', gap: spacing[3], padding: spacing[5] }, compact: { minHeight: 120 }, center: { textAlign: 'center' }, alert: { padding: spacing[3] }, alertRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing[2] }, alertText: { flex: 1, gap: spacing[1] } });
