# Generated by Django 5.1.15 on 2025-12-10 03:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp du dernier message (pour tri)', verbose_name='Dernier message à')),
                ('unread_count_user', models.PositiveIntegerField(default=0, help_text="Nombre de messages admin/système non lus par l'utilisateur", verbose_name='Messages non lus (utilisateur)')),
                ('unread_count_admin', models.PositiveIntegerField(default=0, help_text="Nombre de messages utilisateur non lus par l'administration", verbose_name='Messages non lus (admin)')),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver pour archiver la conversation', verbose_name='Conversation active')),
                ('user', models.OneToOneField(help_text='Utilisateur propriétaire de cette conversation (unique)', on_delete=django.db.models.deletion.CASCADE, related_name='support_conversation', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'chat_conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(blank=True, db_index=True, help_text='UUID généré côté mobile pour déduplication offline. Constraint UNIQUE empêche les doublons lors de la synchronisation.', null=True, unique=True, verbose_name='UUID client')),
                ('sender_type', models.CharField(choices=[('user', 'Utilisateur'), ('admin', 'Administrateur'), ('system', 'Système')], help_text='Qui a envoyé le message', max_length=10, verbose_name="Type d'expéditeur")),
                ('content', models.TextField(help_text='Texte du message (max 5000 caractères)', max_length=5000, verbose_name='Contenu')),
                ('media_type', models.CharField(choices=[('none', 'Aucun média'), ('image', 'Image'), ('video', 'Vidéo')], default='none', max_length=10, verbose_name='Type de média')),
                ('media_file', models.FileField(blank=True, help_text='Image ou vidéo attachée (formats: JPG, PNG, WebP, MP4, MOV)', null=True, upload_to='chat_media/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov'])], verbose_name='Fichier média')),
                ('is_read', models.BooleanField(default=False, help_text='Indique si le destinataire a lu le message', verbose_name='Message lu')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp de lecture du message', null=True, verbose_name='Lu à')),
                ('created_offline', models.BooleanField(default=False, help_text='Indique si le message a été créé hors connexion sur le mobile', verbose_name='Créé offline')),
                ('synced_at', models.DateTimeField(blank=True, help_text='Timestamp de synchronisation avec le serveur', null=True, verbose_name='Synchronisé à')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Conversation')),
                ('sender_user', models.ForeignKey(blank=True, help_text='Utilisateur admin qui a envoyé le message (si sender_type=admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='chat_conv_last_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active', '-last_message_at'], name='chat_conv_active_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_msg_conv_date_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_uuid'], name='chat_msg_client_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'sender_type'], name='chat_msg_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='chat_msg_conv_date_rev_idx'),
        ),
    ]
